"""update phone_number

Revision ID: d1e0d3fa2a6e
Revises: 93644b6748f4
Create Date: 2024-07-24 19:06:43.238389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e0d3fa2a6e'
down_revision: Union[str, None] = '93644b6748f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('phone_number', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'posts', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'phone_number')
    # ### end Alembic commands ###
